template_function: DV._.template
embed_assets:      datauri
gzip_assets:       off

javascripts:
  viewer:
    - public/javascripts/DV/vendor/jquery/dist/jquery.js
    - public/javascripts/DV/vendor/jquery-migrate-1.4.1.min.js
    - public/javascripts/DV/vendor/jquery-ui/ui/version.js
    - public/javascripts/DV/vendor/jquery-ui/ui/widget.js
    - public/javascripts/DV/vendor/jquery-ui/ui/position.js
    - public/javascripts/DV/vendor/jquery-ui/ui/data.js
    - public/javascripts/DV/vendor/jquery-ui/ui/disable-selection.js
    - public/javascripts/DV/vendor/jquery-ui/ui/focusable.js
    - public/javascripts/DV/vendor/jquery-ui/ui/form-reset-mixin.js
    - public/javascripts/DV/vendor/jquery-ui/ui/keycode.js
    - public/javascripts/DV/vendor/jquery-ui/ui/labels.js
    - public/javascripts/DV/vendor/jquery-ui/ui/scroll-parent.js
    - public/javascripts/DV/vendor/jquery-ui/ui/tabbable.js
    - public/javascripts/DV/vendor/jquery-ui/ui/unique-id.js
    - public/javascripts/DV/vendor/jquery-ui/ui/widgets/mouse.js
    - public/javascripts/DV/vendor/jquery-ui/ui/widgets/slider.js
    - public/javascripts/DV/vendor/jquery-ui/ui/effect.js
    - public/javascripts/DV/vendor/jquery-ui/ui/effects/effect-blind.js
    - public/javascripts/DV/vendor/underscore/underscore.js
    - public/javascripts/DV/vendor/jquery.acceptInput.js
    - public/javascripts/DV/vendor/jquery.placeholder.js
    - public/javascripts/DV/lib/initializer.js
    - public/javascripts/DV/lib/*.js
    - public/javascripts/DV/schema/*.js
    - public/javascripts/DV/elements/*.js
    - public/javascripts/DV/models/*.js
    - public/javascripts/DV/events/events.js
    - public/javascripts/DV/events/View*.js
    - public/javascripts/DV/events/*.js
    - public/javascripts/DV/helpers/helpers.js
    - public/javascripts/DV/helpers/*.js
    - public/javascripts/DV/states/*.js
    - public/javascripts/DV/controllers/*.js
  templates:
    - public/javascripts/DV/views/*.jst

stylesheets:
  viewer:
    - public/stylesheets/DV/components/reset.css
    - public/stylesheets/DV/components/structure.css
    - public/stylesheets/DV/components/annotations.css
    - public/stylesheets/DV/components/pages.css
    - public/stylesheets/DV/components/ui.css
    - public/stylesheets/DV/components/ui-*.css
    - public/stylesheets/DV/components/view-*.css
    - public/stylesheets/DV/components/unsupported.css
    - public/stylesheets/DV/components/minimode.css
    - public/stylesheets/DV/themes/plain.css
  print:
    - public/stylesheets/DV/print.css
